# Generated by Django 4.2.22 on 2025-06-10 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('manager', 'マネージャー'), ('developer', '開発者'), ('designer', 'デザイナー'), ('tester', 'テスター'), ('other', 'その他')], default='other', max_length=20, verbose_name='役職')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='プロフィール画像')),
                ('skills', models.TextField(blank=True, help_text='カンマ区切りで入力', verbose_name='スキル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
    ]
