# Generated by Django 4.2.22 on 2025-06-10 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='クライアント名')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('in_progress', '進行中'), ('completed', '完了'), ('on_hold', '保留中'), ('cancelled', 'キャンセル')], default='planning', max_length=20, verbose_name='ステータス')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='予算')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='プロジェクトマネージャー')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
    ]
